version: '3'
services:
  database:
    build: ./database
    image: birdsightingsdatabase:latest
  webserver:
    build: ../BirdSightings
    image: birdsightingswebserver:latest
    depends_on:
        - database
    ports:
        - "8080:80"
